version: "3.7"
services:
  okidro-api:
    build: .
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: pass
      DATABASE_HOST: okidro-mysql
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - okidro-mysql
    #こいつは自動でサーバが立ち上がるようにするやつ。buildのときはいらない
    #command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: on

  okidro-mysql:
    image: mysql/mysql-server:latest
    platform: linux/amd64
    restart: always
    command: mysqld --innodb_use_native_aio=0
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - okidro-mysql:/var/lib/mysql
volumes:
  okidro-mysql:
    driver: local
