version: "3.7"
services:
  okidro-api:
    build: .
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: pass
      DATABASE_HOST: okidro-mysql
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - okidro-mysql
    #こいつは自動でサーバが立ち上がるようにするやつ。buildのときはいらない
    #command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: on

  okidro-mysql:
    image: mysql:8.0.16
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - okidro-mysql:/var/lib/mysql
volumes:
  okidro-mysql:
    driver: local
